/*
PAI: EMPRESA COM TERRITORIO NACIONAL
FILHO: REGIAO DE VENDA COM ZONA DE VENDA 
FILHO 2: ZONA DE VENDA COM UM VENDEDOR

VENDEDOR COM PRODUTO E COMISSAO (COMISSAO = Nº CLIENTE)
PRODUTO COM UMA CATEGORIA
CATEGORIA DE PRODUTO COM O NOME DO VENDEDOR 

REPRESENTANTE COM UM NUMERO X (RESPECTIVO A SUA ZONA) DE UMA REGIAO DE VENDAS COM N ZONAS DE VENDAS
O REPRESENTANTE RECEBE COMISSAO POR QUALQUER PRODUTO EM SUA AREA

CLIENTE (CADASTRO E INFORMA SUA ZONA) SIGNIFICA QUE É ALOCADO PARA X REPRESENTANTE DE VENDA E POR CONSEQUENCIA UM VENDEDOR // PODE DESFAZER COMPRA (TRUE OU FALSE)

calcular comissao 
vendedor = (comissao pela quantidade de produtos vendidos * 0,05) + (nº de clientes cadastrados * 0,05)



*/